window.PUBLICATIONS = [
  {
    number: 35,
    type: "preprint",
    year: 2026,
    title: "A constrained Onsager variational framework for parametric approximations of Willmore and Helfrich flows",
    collaborators: "",
    venue: "arXiv:2608.07244",
    link: "https://arxiv.org/abs/2608.07244",
    featured: true,
  },
  {
    number: 34,
    type: "preprint",
    year: 2026,
    title: "A unified energy-stable finite element approximation for evolving fluidic biomembranes",
    collaborators: "H. Garcke and R. Nürnberg",
    venue: "arXiv:2607.05998",
    link: "https://arxiv.org/abs/2607.05998",
    featured: true,
  },
  {
    number: 33,
    type: "preprint",
    year: 2026,
    title: "A minimizing-movement framework for geometric gradient flows with admissible tangential motion",
    collaborators: "X. Liu",
    venue: "arXiv:2606.18177",
    link: "https://arxiv.org/abs/2606.18177",
  },
  {
    number: 32,
    type: "preprint",
    year: 2026,
    title: "Geometric structure-preserving parametric finite element approximations for the constrained Helfrich flow",
    collaborators: "X. Liu",
    venue: "arXiv:2606.16697",
    link: "https://arxiv.org/abs/2606.16697",
  },
  {
    number: 31,
    type: "published",
    year: 2026,
    title: "Variational modeling and numerical simulations for evaporating thin droplets and coffee-ring effect",
    collaborators: "Y. Li and T. Qian",
    venue: "Eur. Phys. J. E, 49, article 57",
    link: "https://doi.org/10.1140/epje/s10189-026-00603-w",
    featured: true,
  },
  {
    number: 30,
    type: "published",
    year: 2026,
    title: "An energy-stable parametric finite element method for Willmore flow with normal-tangential velocity splitting",
    collaborators: "H. Garcke and R. Nürnberg",
    venue: "SIAM J. Sci. Comput., 48(3), A1235–A1259",
    link: "https://doi.org/10.1137/25M1773878",
    featured: true,
  },
  {
    number: 29,
    type: "published",
    year: 2026,
    title: "Stable fully practical finite element methods for axisymmetric Willmore flow",
    collaborators: "H. Garcke and R. Nürnberg",
    venue: "Comput. Math. Appl., 212, 128–145",
    link: "https://doi.org/10.1016/j.camwa.2026.03.028",
  },
  {
    number: 28,
    type: "published",
    year: 2026,
    title: "A variational front-tracking method for multiphase flow with triple junctions",
    collaborators: "H. Garcke and R. Nürnberg",
    venue: "Math. Comp., 95(358), 647–682",
    link: "https://doi.org/10.1090/mcom/4078",
  },
  {
    number: 27,
    type: "published",
    year: 2026,
    title: "Thermodynamically consistent modeling and stable ALE approximations of reactive semi-permeable interfaces",
    collaborators: "W. Shi, S. Xu and Z. Zhang",
    venue: "Comput. Methods Appl. Mech. Eng., 448, article 118512",
    link: "https://arxiv.org/abs/2507.14774",
  },
  {
    number: 26,
    type: "published",
    year: 2025,
    title: "Stable fully discrete finite element methods with BGN tangential motion for Willmore flow of planar curves",
    collaborators: "H. Garcke and R. Nürnberg",
    venue: "J. Sci. Comput., 105(2), article 45",
    link: "https://arxiv.org/abs/2503.23152",
  },
  {
    number: 25,
    type: "published",
    year: 2025,
    title: "A structure-preserving parametric finite element method for solid-state dewetting on curved substrates",
    collaborators: "Y. Li and W. Bao",
    venue: "Commun. Nonlinear Sci. Numer. Simul., 146, article 108767",
    link: "https://doi.org/10.1016/j.cnsns.2025.108767",
  },
  {
    number: 24,
    type: "published",
    year: 2024,
    title: "Dynamics of small solid particles on substrates of arbitrary topography",
    collaborators: "W. Jiang, Y. Wang, T. Qian, D. J. Srolovitz and W. Bao",
    venue: "Acta Materialia, 281, article 120407",
    link: "https://doi.org/10.1016/j.actamat.2024.120407",
  },
  {
    number: 23,
    type: "published",
    year: 2024,
    title: "Parametric finite element approximations for anisotropic surface diffusion with axisymmetric geometry",
    collaborators: "M. Li",
    venue: "J. Comput. Phys., 497, article 112632",
    link: "https://doi.org/10.1016/j.jcp.2023.112632",
  },
  {
    number: 22,
    type: "published",
    year: 2024,
    title: "Arbitrary Lagrangian–Eulerian finite element approximations for axisymmetric two-phase flow",
    collaborators: "H. Garcke and R. Nürnberg",
    venue: "Comput. Math. Appl., 155, 209–223",
    link: "https://doi.org/10.1016/j.camwa.2023.12.013",
  },
  {
    number: 21,
    type: "published",
    year: 2023,
    title: "Unfitted finite element methods for axisymmetric two-phase flow",
    collaborators: "H. Garcke and R. Nürnberg",
    venue: "J. Sci. Comput., 97, article 14",
    link: "https://doi.org/10.1007/s10915-023-02325-z",
  },
  {
    number: 20,
    type: "published",
    year: 2023,
    title: "Structure-preserving discretizations for two-phase Navier–Stokes flow using fitted and unfitted mesh approaches",
    collaborators: "H. Garcke and R. Nürnberg",
    venue: "J. Comput. Phys., 489, article 112276",
    link: "https://doi.org/10.1016/j.jcp.2023.112276",
  },
  {
    number: 19,
    type: "published",
    year: 2023,
    title: "A diffuse-interface approach for solid-state dewetting with anisotropic surface energies",
    collaborators: "H. Garcke, P. Knopf and R. Nürnberg",
    venue: "J. Nonlinear Sci., 33, article 34",
    link: "https://doi.org/10.1007/s00332-023-09889-y",
  },
  {
    number: 18,
    type: "published",
    year: 2023,
    title: "An energy-stable parametric finite element method for simulating solid-state dewetting in three dimensions",
    collaborators: "W. Bao",
    venue: "J. Comput. Math., 41, 771–796",
    link: "https://doi.org/10.4208/jcm.2205-m2021-0237",
  },
  {
    number: 17,
    type: "published",
    year: 2023,
    title: "A structure-preserving finite element method of surface diffusion for curve networks and surface clusters",
    collaborators: "W. Bao, H. Garcke and R. Nürnberg",
    venue: "Numer. Methods Partial Differential Equations, 39, 759–794",
    link: "https://doi.org/10.1002/num.22921",
  },
  {
    number: 16,
    type: "published",
    year: 2022,
    title: "A level set method for the simulation of moving contact line in three dimensions",
    collaborators: "S. Xu and W. Ren",
    venue: "Commun. Comput. Phys., 32, 1310–1331",
    link: "https://doi.org/10.4208/cicp.OA-2022-0021",
  },
  {
    number: 15,
    type: "published",
    year: 2022,
    title: "Volume-preserving parametric finite element methods for axisymmetric geometric evolution equations",
    collaborators: "W. Bao, H. Garcke and R. Nürnberg",
    venue: "J. Comput. Phys., 460, article 111180",
    link: "https://doi.org/10.1016/j.jcp.2022.111180",
  },
  {
    number: 14,
    type: "published",
    year: 2021,
    title: "A structure-preserving parametric finite element method for surface diffusion",
    collaborators: "W. Bao",
    venue: "SIAM J. Numer. Anal., 59, 2775–2799",
    link: "https://doi.org/10.1137/21M140675",
  },
  {
    number: 13,
    type: "published",
    year: 2021,
    title: "A thermodynamically consistent model and its conservative numerical approximation for moving contact lines with soluble surfactant",
    collaborators: "W. Ren and Z. Zhang",
    venue: "Comput. Methods Appl. Mech. Eng., 385, article 114033",
    link: "https://doi.org/10.1016/j.cma.2021.114033",
  },
  {
    number: 12,
    type: "published",
    year: 2021,
    title: "A finite element method for electrowetting on dielectric",
    collaborators: "W. Ren",
    venue: "J. Comput. Phys., 429, article 109998",
    link: "https://doi.org/10.1016/j.jcp.2020.109998",
  },
  {
    number: 11,
    type: "published",
    year: 2021,
    title: "A θ-L formulation-based finite element method for axisymmetric solid-state dewetting",
    collaborators: "W. Huang and W. Jiang",
    venue: "East Asian J. Appl. Math., 11, 389–405",
    link: "https://doi.org/10.4208/eajam.130920.071220",
  },
  {
    number: 10,
    type: "published",
    year: 2021,
    title: "An energy-stable parametric finite element method for simulating solid-state dewetting",
    collaborators: "W. Jiang and W. Bao",
    venue: "IMA J. Numer. Anal., 41, 2026–2055",
    link: "https://doi.org/10.1093/imanum/draa070",
  },
  {
    number: 9,
    type: "published",
    year: 2020,
    title: "An energy-stable finite element method for the simulation of moving contact lines in two-phase flows",
    collaborators: "W. Ren",
    venue: "J. Comput. Phys., 417, article 109582",
    link: "https://doi.org/10.1016/j.jcp.2020.109582",
  },
  {
    number: 8,
    type: "published",
    year: 2020,
    title: "A parametric finite element method for solid-state dewetting in three dimensions",
    collaborators: "W. Jiang and W. Bao",
    venue: "SIAM J. Sci. Comput., 42, B327–B352",
    link: "https://doi.org/10.1137/19M128166",
  },
  {
    number: 7,
    type: "published",
    year: 2020,
    title: "Sharp-interface model for simulating solid-state dewetting in three dimensions",
    collaborators: "W. Jiang and W. Bao",
    venue: "SIAM J. Appl. Math., 80, 1654–1677",
    link: "https://doi.org/10.1137/19M1251345",
  },
  {
    number: 6,
    type: "published",
    year: 2019,
    title: "A sharp-interface model and its numerical approximation for solid-state dewetting with axisymmetric geometry",
    collaborators: "",
    venue: "J. Comput. Appl. Math., 361, 144–156",
    link: "https://doi.org/10.1016/j.cam.2019.04.008",
  },
  {
    number: 5,
    type: "published",
    year: 2019,
    title: "Sharp-interface approach for simulating solid-state dewetting in two dimensions: a Cahn–Hoffman ξ-vector formulation",
    collaborators: "W. Jiang",
    venue: "Physica D, 390, 69–83",
    link: "https://doi.org/10.1016/j.physd.2018.11.003",
  },
  {
    number: 4,
    type: "published",
    year: 2019,
    title: "Application of Onsager's variational principle to the dynamics of a solid toroidal island on a substrate",
    collaborators: "W. Jiang, T. Qian, D. J. Srolovitz and W. Bao",
    venue: "Acta Materialia, 163, 154–160",
    link: "https://doi.org/10.1016/j.actamat.2018.10.004",
  },
  {
    number: 3,
    type: "published",
    year: 2017,
    title: "Triple junction drag effects during topological changes in the evolution of polycrystalline microstructures",
    collaborators: "W. Jiang, W. Bao and D. J. Srolovitz",
    venue: "Acta Materialia, 128, 345–350",
    link: "https://doi.org/10.1016/j.actamat.2017.02.010",
  },
  {
    number: 2,
    type: "published",
    year: 2017,
    title: "A parametric finite element method for solid-state dewetting problems with anisotropic surface energies",
    collaborators: "W. Bao, W. Jiang and Y. Wang",
    venue: "J. Comput. Phys., 330, 380–400",
    link: "https://doi.org/10.1016/j.jcp.2016.11.015",
  },
  {
    number: 1,
    type: "published",
    year: 2016,
    title: "Solid-state dewetting and island morphologies in strongly anisotropic materials",
    collaborators: "W. Jiang, Y. Wang, W. Bao and D. J. Srolovitz",
    venue: "Scripta Materialia, 115, 123–127",
    link: "https://doi.org/10.1016/j.scriptamat.2016.01.018",
  },
];
